farm/urls.py
from django.urls import path
from seeplahar.views.generic import GenericListView, GenericDetailView, GenericCreateView, GenericUpdateView, GenericDeleteView
from .models import SeedLot, Planting, Harvest, SeedlingBatch, Event
from .views import GenerateQRCodeView, IntakeView, EventCreateView, EventUpdateView

app_name = 'farm'

urlpatterns = [
    # SeedLot URLs
    path('seedlots/', GenericListView.as_view(model=SeedLot), name='seedlot_list'),
    path('seedlots/<uuid:pk>/', GenericDetailView.as_view(model=SeedLot), name='seedlot_detail'),
    path('seedlots/add/', GenericCreateView.as_view(model=SeedLot, fields=['variety', 'name', 'quantity', 'units', 'date_received', 'origin', 'description', 'source_partner', 'source']), name='seedlot_create'),
    path('seedlots/<uuid:pk>/update/', GenericUpdateView.as_view(model=SeedLot, fields=['variety', 'name', 'quantity', 'units', 'date_received', 'origin', 'description', 'source_partner', 'source']), name='seedlot_update'),
    path('seedlots/<uuid:pk>/delete/', GenericDeleteView.as_view(model=SeedLot), name='seedlot_delete'),

    # Planting URLs
    path('plants/', GenericListView.as_view(model=Planting), name='planting_list'),
    path('plants/<uuid:pk>/', GenericDetailView.as_view(model=Planting), name='planting_detail'),
    path('plants/add/', GenericCreateView.as_view(model=Planting, fields=['source_partner', 'variety', 'date', 'location', 'status', 'source_content_type', 'source_object_id']), name='planting_create'),
    path('plants/<uuid:pk>/update/', GenericUpdateView.as_view(model=Planting, fields=['source_partner', 'variety', 'date', 'location', 'status', 'source_content_type', 'source_object_id']), name='planting_update'),
    path('plants/<uuid:pk>/delete/', GenericDeleteView.as_view(model=Planting), name='planting_delete'),

    # Harvest URLs
    path('harvests/', GenericListView.as_view(model=Harvest), name='harvest_list'),
    path('harvests/<uuid:pk>/', GenericDetailView.as_view(model=Harvest), name='harvest_detail'),
    path('harvests/add/', GenericCreateView.as_view(model=Harvest, fields=['plants', 'date', 'quantity', 'units', 'description', 'source_partner']), name='harvest_create'),
    path('harvests/<uuid:pk>/update/', GenericUpdateView.as_view(model=Harvest, fields=['plants', 'date', 'quantity', 'units', 'description', 'source_partner']), name='harvest_update'),
    path('harvests/<uuid:pk>/delete/', GenericDeleteView.as_view(model=Harvest), name='harvest_delete'),

    # SeedlingBatch URLs
    path('seedlingbatches/', GenericListView.as_view(model=SeedlingBatch), name='seedlingbatch_list'),
    path('seedlingbatches/<uuid:pk>/', GenericDetailView.as_view(model=SeedlingBatch), name='seedlingbatch_detail'),
    path('seedlingbatches/add/', GenericCreateView.as_view(model=SeedlingBatch, fields=['seed_lot', 'date', 'quantity', 'units', 'location', 'status', 'parent_batch', 'source', 'variety']), name='seedlingbatch_create'),
    path('seedlingbatches/<uuid:pk>/update/', GenericUpdateView.as_view(model=SeedlingBatch, fields=['seed_lot', 'date', 'quantity', 'units', 'location', 'status', 'parent_batch', 'source', 'variety']), name='seedlingbatch_update'),
    path('seedlingbatches/<uuid:pk>/delete/', GenericDeleteView.as_view(model=SeedlingBatch), name='seedlingbatch_delete'),

    # Event URLs
    path('events/', GenericListView.as_view(model=Event), name='event_list'),
    path('events/<uuid:pk>/', GenericDetailView.as_view(model=Event), name='event_detail'),
    path('events/add/', EventCreateView.as_view(), name='event_create'),
    path('events/<uuid:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('events/<uuid:pk>/delete/', GenericDeleteView.as_view(model=Event), name='event_delete'),

    # Special views
    path('generate_qr/<uuid:pk>/', GenerateQRCodeView.as_view(), name='generate_qr'),
    path('intake/', IntakeView.as_view(), name='intake'),
]

seeplahar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views.specific import (
    HomePageView, custom_logout, CustomLoginView, DashboardView
)
from .views.generic import (
    GenericListView, GenericDetailView, GenericCreateView, GenericUpdateView, GenericDeleteView
)
from autocomplete import HTMXAutoComplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('taxon/', include('taxon.urls', namespace='taxon')),
    path('farm/', include('farm.urls', namespace='farm')),
    # path('shop/', include('shop.urls', namespace='shop')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', custom_logout, name='logout'),
    path('<uuid:pk>/', GenericDetailView.as_view(), name='generic-detail'),
    path('users/', include('users.urls', namespace='users')),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    *HTMXAutoComplete.url_dispatcher('ac'),

    # New generic URL patterns
    path('<str:app_name>/<str:model_name>/', GenericListView.as_view(), name='generic_list'),
    path('<str:app_name>/<str:model_name>/create/', GenericCreateView.as_view(), name='generic_create'),
    path('<str:app_name>/<str:model_name>/<uuid:pk>/', GenericDetailView.as_view(), name='generic_detail'),
    path('<str:app_name>/<str:model_name>/<uuid:pk>/update/', GenericUpdateView.as_view(), name='generic_update'),
    path('<str:app_name>/<str:model_name>/<uuid:pk>/delete/', GenericDeleteView.as_view(), name='generic_delete'),
]

taxon/urls.py
from django.urls import path
from .views import (
    TaxonListView, VarietyDetailView, VarietyListView, TaxonDetailView, TaxonTestListView, VarietyCreateView,
    TaxonCreateView, SynonymCreateView, CharacteristicNameAutoComplete, CharacteristicValueAutoComplete,
    add_characteristic_form, test_autocomplete
)
import uuid

# taxon/urls.py

app_name = 'taxon'

urlpatterns = [
    path('variety/<uuid:pk>/', VarietyDetailView.as_view(), name='variety-detail'),
    path('taxon/<uuid:pk>/', TaxonDetailView.as_view(), name='taxon-detail'),
    path('<str:type>/<uuid:taxon_id>/', VarietyListView.as_view(), name='variety-list'),
    path('add_variety/', VarietyCreateView.as_view(), name='variety_create'),
    path('add_taxon/', TaxonCreateView.as_view(), name='taxon_create'),
    path('add_synonym/', SynonymCreateView.as_view(), name='synonym_create'),
    path('add_characteristic_form/', add_characteristic_form, name='add_characteristic_form'),
    path('characteristic-name-autocomplete/', CharacteristicNameAutoComplete.as_view(), name='characteristicNameAutoComplete'),
    path('characteristic-value-autocomplete/', CharacteristicValueAutoComplete.as_view(), name='characteristicValueAutoComplete'),
    path('<str:type>/', TaxonListView.as_view(), name='taxon-list'),

]

seeplahar/views.py
from taxon.models import Photo
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth import login as auth_login
from taxon.models import Variety
from farm.models import Event, Plant, SeedLot, SeedlingBatch, Harvest
from django.contrib.auth import logout
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm

class CustomLoginView(View):
    def get(self, request, *args, **kwargs):
        form = AuthenticationForm()
        return render(request, 'registration/login.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('/')
        return render(request, 'registration/login.html', {'form': form})
def custom_logout(request):
    logout(request)
    return redirect('/')

class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['types'] = [
            {
                'name': 'Fruits',
                'url': reverse_lazy('taxon:taxon-list', kwargs={'type': 'fruit'}),
                'image': '/static/images/fruit.jpg'
            },
            {
                'name': 'Vegetables',
                'url': reverse_lazy('taxon:taxon-list', kwargs={'type': 'vegetable'}),
                'image': '/static/images/vegetable.jpg'
            },
            {
                'name': 'Herbs',
                'url': reverse_lazy('taxon:taxon-list', kwargs={'type': 'herb'}),
                'image': '/static/images/herb.jpg'
            },
            {
                'name': 'Flowers',
                'url': reverse_lazy('taxon:taxon-list', kwargs={'type': 'flower'}),
                'image': '/static/images/flower.jpg'
            },
        ]
        return context


class GenericDetailView(View):

    def get(self, request, *args, **kwargs):
        uuid = kwargs.get('pk')

        # Try to get a Variety
        try:
            variety = Variety.objects.get(pk=uuid)
            return HttpResponseRedirect(reverse('taxon:variety-detail', kwargs={'pk': uuid}))
        except Variety.DoesNotExist:
            pass

        # Try to get other farm objects and redirect accordingly
        try:
            event = Event.objects.get(pk=uuid)
            return HttpResponseRedirect(reverse('farm:event-add', kwargs={'pk': uuid}))
        except Event.DoesNotExist:
            pass

        try:
            plant = Plant.objects.get(pk=uuid)
            return HttpResponseRedirect(reverse('farm:plant-detail', kwargs={'pk': uuid}))
        except Plant.DoesNotExist:
            pass

        try:
            seed_lot = SeedLot.objects.get(pk=uuid)
            return HttpResponseRedirect(reverse('farm:seedlot-detail', kwargs={'pk': uuid}))
        except SeedLot.DoesNotExist:
            pass

        try:
            seedling_batch = SeedlingBatch.objects.get(pk=uuid)
            return HttpResponseRedirect(reverse('farm:seedlingbatch-detail', kwargs={'pk': uuid}))
        except SeedlingBatch.DoesNotExist:
            pass

        try:
            harvest = Harvest.objects.get(pk=uuid)
            return HttpResponseRedirect(reverse('farm:harvest-detail', kwargs={'pk': uuid}))
        except Harvest.DoesNotExist:
            pass

        raise Http404("Object does not exist")

seeplahar/views/base.py
# seeplahar/views/base.py

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from users.middleware import get_current_customer

class CustomerAwareView(LoginRequiredMixin):
    def get_queryset(self):
        if self.request.user.is_superuser:
            return super().get_queryset()
        else:
            return super().get_queryset().filter(customer=get_current_customer())

class BaseListView(CustomerAwareView, ListView):
    template_name = 'base_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view'] = self
        return context

class BaseDetailView(CustomerAwareView, DetailView):
    template_name = 'base_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view'] = self
        return context

class BaseCreateView(CustomerAwareView, CreateView):
    template_name = 'base_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view'] = self
        context['action'] = 'Create'
        return context

    def get_success_url(self):
        return reverse_lazy(f'{self.model._meta.app_label}:{self.model._meta.model_name}_detail', kwargs={'pk': self.object.pk})

class BaseUpdateView(CustomerAwareView, UpdateView):
    template_name = 'base_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view'] = self
        context['action'] = 'Update'
        return context

    def get_success_url(self):
        return reverse_lazy(f'{self.model._meta.app_label}:{self.model._meta.model_name}_detail', kwargs={'pk': self.object.pk})

class BaseDeleteView(CustomerAwareView, DeleteView):
    template_name = 'base_confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view'] = self
        return context

    def get_success_url(self):
        return reverse_lazy(f'{self.model._meta.app_label}:{self.model._meta.model_name}_list')

seeplahar/views/generic.py
from django.apps import apps
from django.http import Http404
from django.urls import reverse

from .base import BaseListView, BaseDetailView, BaseCreateView, BaseUpdateView, BaseDeleteView


class GenericModelView:
    def dispatch(self, request, *args, **kwargs):
        self.app_name = self.model._meta.app_label
        self.model_name = self.model._meta.model_name
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_fields'] = [
            {'name': field.name, 'verbose_name': field.verbose_name}
            for field in self.model._meta.fields
        ]
        context['model_name'] = self.model._meta.verbose_name
        context['model_name_plural'] = self.model._meta.verbose_name_plural
        context['app_label'] = self.app_name

        # Generate URL names
        base_name = f"{self.app_name}:{self.model_name}"
        context['list_url_name'] = f"{base_name}_list"
        context['detail_url_name'] = f"{base_name}_detail"
        context['create_url_name'] = f"{base_name}_create"
        context['update_url_name'] = f"{base_name}_update"
        context['delete_url_name'] = f"{base_name}_delete"

        return context


class GenericListView(GenericModelView, BaseListView):
    template_name = 'base_list.html'


class GenericDetailView(GenericModelView, BaseDetailView):
    template_name = 'base_detail.html'


class GenericCreateView(GenericModelView, BaseCreateView):
    template_name = 'base_form.html'


class GenericUpdateView(GenericModelView, BaseUpdateView):
    template_name = 'base_form.html'


class GenericDeleteView(GenericModelView, BaseDeleteView):
    template_name = 'base_confirm_delete.html'

    def get_success_url(self):
        return reverse(f'{self.model._meta.app_label}:{self.model._meta.model_name}_list')

seeplahar/views/specific.py
from taxon.models import Photo
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth import login as auth_login
from taxon.models import Variety
from farm.models import Event, Planting, SeedLot, SeedlingBatch, Harvest
from django.contrib.auth import logout
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import PermissionRequiredMixin


class CustomLoginView(View):
    def get(self, request, *args, **kwargs):
        form = AuthenticationForm()
        return render(request, 'registration/login.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('/')
        return render(request, 'registration/login.html', {'form': form})

def custom_logout(request):
    logout(request)
    return redirect('/')

class DashboardView(PermissionRequiredMixin, TemplateView):
    template_name = 'dashboard.html'
    permission_required = ('farm.add_seedlot', 'taxon.add_variety')
    raise_exception = True  # Raise a 403 Forbidden if permission is denied

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['has_perm'] = self.request.user.has_perm
        return context

class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['types'] = [
            {
                'name': 'Fruits',
                'url': reverse_lazy('taxon:taxon-list', kwargs={'type': 'fruit'}),
                'image': '/static/images/fruit.jpg'
            },
            {
                'name': 'Vegetables',
                'url': reverse_lazy('taxon:taxon-list', kwargs={'type': 'vegetable'}),
                'image': '/static/images/vegetable.jpg'
            },
            {
                'name': 'Herbs',
                'url': reverse_lazy('taxon:taxon-list', kwargs={'type': 'herb'}),
                'image': '/static/images/herb.jpg'
            },
            {
                'name': 'Flowers',
                'url': reverse_lazy('taxon:taxon-list', kwargs={'type': 'flower'}),
                'image': '/static/images/flower.jpg'
            },
        ]
        return context

seeplahar/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load custom_tags %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Seeplahar{% endblock %}</title>
    <script src="{% static 'js/htmx.min.js' %}"></script>


    {% load static tailwind_tags %}
    {% load permissions %}
    {% tailwind_css %}

    <style>
        html, body {
            margin: 0;
            padding: 0;
            height: 100%;
        }
    </style>
</head>
<body class="bg-primary-lighter text-primary-dark flex flex-col min-h-screen">

    <div class="flex-grow">
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
</body>
</html>

seeplahar/templates/base_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete {{ model_name|title }}</h1>
<p>Are you sure you want to delete the {{ model_name }} "{{ object }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Confirm Delete</button>
</form>
<a href="{% url app_label|add:':'|add:model_name|add:'_list' %}">Cancel</a>
{% endblock %}

seeplahar/templates/base_detail.html
{% extends "base.html" %}
{% load custom_tags %}

{% block content %}
  <h1>{{ object }}</h1>
  
  <dl>
    {% for field in model_fields %}
      <dt>{{ field.verbose_name|title }}</dt>
      <dd>{{ object|getattribute:field.name }}</dd>
    {% endfor %}
  </dl>

  <a href="{% url 'generic_update' app_label model_name object.pk %}">Edit</a>
  <a href="{% url 'generic_delete' app_label model_name object.pk %}">Delete</a>
  <a href="{% url 'generic_list' app_label model_name %}">Back to List</a>
{% endblock %}

seeplahar/templates/base_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ action }} {{ model_name|title }}</h1>
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
  
  <a href="{% url app_label|add:':'|add:model_name|add:'_list' %}">Cancel</a>
{% endblock %}

seeplahar/templates/base_list.html
{% extends "base.html" %}
{% load custom_tags %}

{% block content %}
<h1>{{ model_name_plural|title }} List</h1>

<table>
    <thead>
        <tr>
            {% for field in model_fields %}
                <th>{{ field.verbose_name|title }}</th>
            {% endfor %}
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
            <tr>
                {% for field in model_fields %}
                    <td>{{ object|getattribute:field.name }}</td>
                {% endfor %}
                <td>
                    <a href="{% url 'generic_detail' app_label model_name object.pk %}">View</a>
                    <a href="{% url 'generic_update' app_label model_name object.pk %}">Edit</a>
                    <a href="{% url 'generic_delete' app_label model_name object.pk %}">Delete</a>
                </td>
            </tr>
        {% empty %}
            <tr><td colspan="{{ model_fields|length|add:1 }}">No {{ model_name_plural }} found.</td></tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'generic_create' app_label model_name %}">Create New {{ model_name|title }}</a>
{% endblock %}

seeplahar/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Admin Dashboard{% endblock %}
{% load permissions %}
{% block content %}
<h1 class="text-3xl font-bold">Admin Dashboard</h1>
<ul>
    {% if user|has_perm:'taxon.add_variety' %}
    <li><a href="{% url 'taxon:variety_create' %}">Add New Variety</a></li>
    <li><a href="{% url 'taxon:taxon_create' %}">Add New Taxon</a></li>
    <li><a href="{% url 'taxon:synonym_create' %}">Add New Synonym</a></li>
    {% endif %}
    {% if user|has_perm:'farm.add_seedlot' %}
    <li><a href="{% url 'farm:seedlot_create' %}">Add New SeedLot</a></li>
    <li><a href="{% url 'farm:seedlingbatch_create' %}">Add New SeedlingBatch</a></li>
    <li><a href="{% url 'farm:plant_create' %}">Add New planting</a></li>
    <li><a href="{% url 'farm:harvest_create' %}">Add New Harvest</a></li>
    {% endif %}
</ul>
{% endblock %}

seeplahar/templates/footer.html
{% load permissions %}

<style>
    /* Ensure dropdown menus stay visible */
    .group:hover .group-hover\:flex {
        display: flex;
    }
    .group:hover .group-hover\:block {
        display: block;
    }
    /* Add a slight delay for hover out to ensure persistence */
    .group .group-hover\:flex:hover,
    .group .group-hover\:block:hover {
        display: flex;
    }

    /* Add hover effects */
    a.relative.group {
        position: relative;
        display: block;
        overflow: hidden;
        border-radius: 10px;
        transition: transform 0.3s ease;
    }

    a.relative.group:hover {
        transform: scale(1.05) rotate(1deg);
    }
</style>

<footer class="bg-primary-dark text-primary-lighter py-4 fixed bottom-0 w-full">
    <div class="container mx-auto">
        <nav class="flex justify-between">
            <ul class="flex space-x-4">
                <!-- HOME icon link -->
                <li class="group relative">
                    <a href="{% url 'home' %}" class="hover:underline p-2 block">
                        <svg class="w-6 h-6 inline-block" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path d="M3 9.75L12 3l9 6.75v11.25a.75.75 0 01-.75.75h-4.5a.75.75 0 01-.75-.75v-5.25H9.75v5.25a.75.75 0 01-.75.75h-4.5a.75.75 0 01-.75-.75V9.75z"></path>
                        </svg>
                    </a>
                </li>
                <li class="group relative">
                    <a href="#" class="hover:underline p-2 block">Type</a>
                    <ul class="absolute left-0 bottom-full -mb-2 hidden group-hover:flex flex-col bg-primary-light p-2 rounded-lg">
                        <li><a href="{% url 'taxon:taxon-list' type='fruit' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Fruits</a></li>
                        <li><a href="{% url 'taxon:taxon-list' type='vegetable' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Vegetables</a></li>
                        <li><a href="{% url 'taxon:taxon-list' type='herb' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Herbs</a></li>
                        <li><a href="{% url 'taxon:taxon-list' type='flower' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Flowers</a></li>
                    </ul>
                </li>
                <li class="group relative">
                    <a href="#" class="hover:underline p-2 block">Farm</a>
                    <ul class="absolute left-0 bottom-full -mb-2 hidden group-hover:flex flex-col bg-primary-light p-2 rounded-lg">
                        <li><a href="#" class="block px-4 py-2 text-primary-dark hover:text-accent">Operations</a></li>
                        <li><a href="#" class="block px-4 py-2 text-primary-dark hover:text-accent">Histories</a></li>
                    </ul>
                </li>
                <li class="group relative">
                    <a href="#" class="hover:underline p-2 block">Shop</a>
                    <ul class="absolute left-0 bottom-full -mb-2 hidden group-hover:flex flex-col bg-primary-light p-2 rounded-lg">
                        <li><a href="#" class="block px-4 py-2 text-primary-dark hover:text-accent">Seeds</a></li>
                        <li><a href="#" class="block px-4 py-2 text-primary-dark hover:text-accent">Produce</a></li>
                    </ul>
                </li>
                {% if user.is_authenticated and user|has_perm:"farm.add_seedlot" %}
                <li class="group relative">
                    <a href="#" class="hover:underline p-2 block">Admin</a>
                    <ul class="absolute left-0 bottom-full -mb-2 hidden group-hover:flex flex-col bg-primary-light p-2 rounded-lg">
                        <li><a href="{% url 'dashboard' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Dashboard</a></li>
                        <li><a href="{% url 'taxon:variety_create' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Add New Variety</a></li>
                        <li><a href="{% url 'taxon:taxon_create' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Add New Taxon</a></li>
                        <li><a href="{% url 'taxon:synonym_create' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Add New Synonym</a></li>
                        <li><a href="{% url 'farm:seedlot_create' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Add New SeedLot</a></li>
                        <li><a href="{% url 'farm:seedlingbatch_create' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Add New SeedlingBatch</a></li>
                        <li><a href="{% url 'farm:planting_create' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Add New planting</a></li>
                        <li><a href="{% url 'farm:harvest_create' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Add New Harvest</a></li>
                        <li><a href="{% url 'farm:intake' %}" class="block px-4 py-2 text-primary-dark hover:text-accent">Intake</a></li> <!-- Added link to intake -->
                    </ul>
                </li>
                {% endif %}
            </ul>
            <ul class="flex space-x-4">
                <!-- Login/Logout link -->
                {% if user.is_authenticated %}
                <li class="group relative">
                    <a href="{% url 'logout' %}" class="hover:underline p-2 block">Logout ({{ user.username }})</a>
                </li>
                {% else %}
                <li class="group relative">
                    <a href="{% url 'login' %}" class="hover:underline p-2 block">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</footer>

seeplahar/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home - Seeplahar{% endblock %}

{% block content %}
<div class="grid grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-4 p-4">
    {% for type in types %}
    <a href="{{ type.url }}" class="relative group">
        <img src="{{ type.image }}" alt="{{ type.name }}" class="w-full h-auto">
        <div class="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
            {{ type.name }}
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}