farm/urls.py
from django.urls import path
from seeplahar.views.generic import GenericListView, GenericDetailView, GenericCreateView, GenericUpdateView, GenericDeleteView
from .models import SeedLot, Planting, Harvest, SeedlingBatch, Event
from .views import GenerateQRCodeView, IntakeView, EventCreateView, EventUpdateView

app_name = 'farm'

urlpatterns = [
    # SeedLot URLs
    path('seedlots/', GenericListView.as_view(model=SeedLot), name='seedlot_list'),
    path('seedlots/<uuid:pk>/', GenericDetailView.as_view(model=SeedLot), name='seedlot_detail'),
    path('seedlots/add/', GenericCreateView.as_view(model=SeedLot, fields=['variety', 'name', 'quantity', 'units', 'date_received', 'origin', 'description', 'source_partner', 'source']), name='seedlot_create'),
    path('seedlots/<uuid:pk>/update/', GenericUpdateView.as_view(model=SeedLot, fields=['variety', 'name', 'quantity', 'units', 'date_received', 'origin', 'description', 'source_partner', 'source']), name='seedlot_update'),
    path('seedlots/<uuid:pk>/delete/', GenericDeleteView.as_view(model=SeedLot), name='seedlot_delete'),

    # Planting URLs
    path('plants/', GenericListView.as_view(model=Planting), name='planting_list'),
    path('plants/<uuid:pk>/', GenericDetailView.as_view(model=Planting), name='planting_detail'),
    path('plants/add/', GenericCreateView.as_view(model=Planting, fields=['source_partner', 'variety', 'date', 'location', 'status', 'source_content_type', 'source_object_id']), name='planting_create'),
    path('plants/<uuid:pk>/update/', GenericUpdateView.as_view(model=Planting, fields=['source_partner', 'variety', 'date', 'location', 'status', 'source_content_type', 'source_object_id']), name='planting_update'),
    path('plants/<uuid:pk>/delete/', GenericDeleteView.as_view(model=Planting), name='planting_delete'),

    # Harvest URLs
    path('harvests/', GenericListView.as_view(model=Harvest), name='harvest_list'),
    path('harvests/<uuid:pk>/', GenericDetailView.as_view(model=Harvest), name='harvest_detail'),
    path('harvests/add/', GenericCreateView.as_view(model=Harvest, fields=['plants', 'date', 'quantity', 'units', 'description', 'source_partner']), name='harvest_create'),
    path('harvests/<uuid:pk>/update/', GenericUpdateView.as_view(model=Harvest, fields=['plants', 'date', 'quantity', 'units', 'description', 'source_partner']), name='harvest_update'),
    path('harvests/<uuid:pk>/delete/', GenericDeleteView.as_view(model=Harvest), name='harvest_delete'),

    # SeedlingBatch URLs
    path('seedlingbatches/', GenericListView.as_view(model=SeedlingBatch), name='seedlingbatch_list'),
    path('seedlingbatches/<uuid:pk>/', GenericDetailView.as_view(model=SeedlingBatch), name='seedlingbatch_detail'),
    path('seedlingbatches/add/', GenericCreateView.as_view(model=SeedlingBatch, fields=['seed_lot', 'date', 'quantity', 'units', 'location', 'status', 'parent_batch', 'source', 'variety']), name='seedlingbatch_create'),
    path('seedlingbatches/<uuid:pk>/update/', GenericUpdateView.as_view(model=SeedlingBatch, fields=['seed_lot', 'date', 'quantity', 'units', 'location', 'status', 'parent_batch', 'source', 'variety']), name='seedlingbatch_update'),
    path('seedlingbatches/<uuid:pk>/delete/', GenericDeleteView.as_view(model=SeedlingBatch), name='seedlingbatch_delete'),

    # Event URLs
    path('events/', GenericListView.as_view(model=Event), name='event_list'),
    path('events/<uuid:pk>/', GenericDetailView.as_view(model=Event), name='event_detail'),
    path('events/add/', EventCreateView.as_view(), name='event_create'),
    path('events/<uuid:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('events/<uuid:pk>/delete/', GenericDeleteView.as_view(model=Event), name='event_delete'),

    # Special views
    path('generate_qr/<uuid:pk>/', GenerateQRCodeView.as_view(), name='generate_qr'),
    path('intake/', IntakeView.as_view(), name='intake'),
]

taxon/urls.py
from django.urls import path
from .views import (
    TaxonListView, VarietyDetailView, VarietyListView, TaxonDetailView, TaxonTestListView, VarietyCreateView,
    TaxonCreateView, SynonymCreateView, CharacteristicNameAutoComplete, CharacteristicValueAutoComplete,
    add_characteristic_form, test_autocomplete
)
import uuid

# taxon/urls.py

app_name = 'taxon'

urlpatterns = [
    path('variety/<uuid:pk>/', VarietyDetailView.as_view(), name='variety-detail'),
    path('taxon/<uuid:pk>/', TaxonDetailView.as_view(), name='taxon-detail'),
    path('<str:type>/<uuid:taxon_id>/', VarietyListView.as_view(), name='variety-list'),
    path('add_variety/', VarietyCreateView.as_view(), name='variety_create'),
    path('add_taxon/', TaxonCreateView.as_view(), name='taxon_create'),
    path('add_synonym/', SynonymCreateView.as_view(), name='synonym_create'),
    path('add_characteristic_form/', add_characteristic_form, name='add_characteristic_form'),
    path('characteristic-name-autocomplete/', CharacteristicNameAutoComplete.as_view(), name='characteristicNameAutoComplete'),
    path('characteristic-value-autocomplete/', CharacteristicValueAutoComplete.as_view(), name='characteristicValueAutoComplete'),
    path('<str:type>/', TaxonListView.as_view(), name='taxon-list'),

]

taxon/models.py
from django.db import models
import uuid
from users.models import CustomerAwareModel
from media.models import Photo

# taxon/models.py

class Taxon(CustomerAwareModel):
    FRUIT = 'fruit'
    VEGETABLE = 'vegetable'
    HERB = 'herb'
    FLOWER = 'flower'
    GRASS = 'grass'
    SHRUB = 'shrub'
    TREE = 'tree'
    SUCCULENT = 'succulent'
    ANNUAL = 'annual'
    PERENNIAL = 'perennial'
    OTHER = 'other'

    TYPE_CHOICES = [
        (FRUIT, 'Fruit'),
        (VEGETABLE, 'Vegetable'),
        (HERB, 'Herb'),
        (FLOWER, 'Flower'),
        (GRASS, 'Grass'),
        (SHRUB, 'Shrub'),
        (TREE, 'Tree'),
        (SUCCULENT, 'Succulent'),
        (ANNUAL, 'Annual'),
        (PERENNIAL, 'Perennial'),
        (OTHER, 'Other'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    species_name = models.CharField(max_length=100)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES, default=OTHER)
    description = models.TextField(blank=True, null=True)
    photos = models.ManyToManyField(Photo, blank=True, related_name='taxons')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Taxa"


class Synonym(CustomerAwareModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    taxon = models.ForeignKey(Taxon, related_name='synonyms', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Variety(CustomerAwareModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    taxon = models.ForeignKey(Taxon, related_name='varieties', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    # origin = models.CharField(max_length=100, blank=True, null=True)
    photos = models.ManyToManyField(Photo, blank=True, related_name='varieties')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Varieties"

class Characteristic(CustomerAwareModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=100)
    varieties = models.ManyToManyField('Variety', related_name='characteristics')

    def __str__(self):
        return f"{self.name}: {self.value}"

taxon/forms.py
from django import forms
from .models import Variety, Taxon, Synonym, Characteristic
from django.forms import inlineformset_factory
from autocomplete import HTMXAutoComplete, widgets

# taxon/forms.py

class VarietyForm(forms.ModelForm):
    class Meta:
        model = Variety
        fields = ['name', 'taxon', 'description', 'photos']

# class CharacteristicForm(forms.ModelForm):
#     class Meta:
#         model = Characteristic
#         fields = ['name', 'value']


class CharacteristicForm(forms.ModelForm):
    class Meta:
        model = Characteristic
        fields = ['name', 'value']
        widgets = {
            'name': widgets.Autocomplete(
                name='characteristic_name',
                options=dict(model=Characteristic, field='name')
            ),
            'value': widgets.Autocomplete(
                name='characteristic_value',
                options=dict(model=Characteristic, field='value')
            )
        }


class TaxonForm(forms.ModelForm):
    class Meta:
        model = Taxon
        fields = ['name', 'species_name', 'type', 'description']

class SynonymForm(forms.ModelForm):
    class Meta:
        model = Synonym
        fields = ['name', 'taxon']

taxon/views.py
import logging
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Taxon, Variety, Synonym, Characteristic
from .forms import VarietyForm, TaxonForm, SynonymForm, CharacteristicForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.forms import modelformset_factory
from django.http import JsonResponse
from autocomplete import HTMXAutoComplete

# taxon/views.py
def add_characteristic_form(request):
    CharacteristicFormSet = modelformset_factory(Characteristic, form=CharacteristicForm, extra=1)
    formset = CharacteristicFormSet(queryset=Characteristic.objects.none())
    return render(request, 'taxon/characteristic_form.html', {'formset': formset})


logger = logging.getLogger(__name__)


# def characteristic_name_autocomplete(request):
#     term = request.GET.get('term', '')
#     print(f"Search term received: {term}")  # Debugging line
#
#     suggestions = Characteristic.objects.filter(name__istartswith=term).values_list('name', flat=True).distinct()
#     return render(request, 'taxon/autocomplete_suggestions.html', {'suggestions': suggestions})
#
#
# def characteristic_value_autocomplete(request):
#     term = request.GET.get('term', '')
#     suggestions = Characteristic.objects.filter(value__istartswith=term).values_list('value', flat=True).distinct()
#     return render(request, 'taxon/autocomplete_suggestions.html', {'suggestions': suggestions})

# def characteristic_name_autocomplete(request):
#     term = request.GET.get('term', '')
#     print(f"Search term received (name): {term}")  # Debugging line
#     if term:
#         suggestions = Characteristic.objects.filter(name__istartswith=term).values_list('name', flat=True).distinct()
#     else:
#         suggestions = Characteristic.objects.values_list('name', flat=True).distinct()
#     return render(request, 'taxon/autocomplete_suggestions.html', {'suggestions': suggestions})
#
#
# def characteristic_value_autocomplete(request):
#     term = request.GET.get('term', '')
#     characteristic_name = request.GET.get('characteristic_name', '')
#     print(f"Search term received (value): {term}, characteristic_name: {characteristic_name}")  # Debugging line
#     if characteristic_name:
#         suggestions = Characteristic.objects.filter(name=characteristic_name, value__istartswith=term).values_list('value', flat=True).distinct()
#     else:
#         suggestions = []
#     return render(request, 'taxon/autocomplete_suggestions.html', {'suggestions': suggestions})

def characteristic_autocomplete(request):
    term = request.GET.get('term', '')
    print(f"Autocomplete search term: {term}")  # Debug print
    if term:
        suggestions = Characteristic.objects.filter(
            name__icontains=term
        ).values('name', 'value').distinct()
        print(f"Autocomplete suggestions: {suggestions}")  # Debug print
        return JsonResponse({'suggestions': list(suggestions)})
    suggestions = Characteristic.objects.all().values('name', 'value').distinct()
    return JsonResponse({'suggestions': list(suggestions)})


class CharacteristicNameAutoComplete(HTMXAutoComplete):
    name = 'characteristic_name'
    route_name = 'characteristic_name_autocomplete'

    class Meta:
        model = Characteristic
        field = 'name'

    def get(self, request, *args, **kwargs):
        term = request.GET.get('term', '')
        print(f"CharacteristicNameAutoComplete search term: {term}")  # Debug print
        if term:
            suggestions = Characteristic.objects.filter(name__icontains=term).values('name', 'value').distinct()
            print(f"CharacteristicNameAutoComplete suggestions: {suggestions}")  # Debug print
            return render(request, 'taxon/autocomplete_suggestions.html', {'suggestions': list(suggestions)})
        suggestions = Characteristic.objects.all().values('name', 'value').distinct()
        return render(request, 'taxon/autocomplete_suggestions.html', {'suggestions': list(suggestions)})

class CharacteristicValueAutoComplete(HTMXAutoComplete):
    name = 'characteristic_value'
    route_name = 'characteristic_value_autocomplete'

    class Meta:
        model = Characteristic
        field = 'value'

    def get(self, request, *args, **kwargs):
        term = request.GET.get('term', '')
        characteristic_name = request.GET.get('characteristic_name', '')
        print(f"CharacteristicValueAutoComplete search term: {term}, characteristic_name: {characteristic_name}")  # Debug print
        if term and characteristic_name:
            suggestions = Characteristic.objects.filter(value__icontains=term, name=characteristic_name).values('value', 'name').distinct()
            print(f"CharacteristicValueAutoComplete suggestions: {suggestions}")  # Debug print
            return render(request, 'taxon/autocomplete_suggestions.html', {'suggestions': list(suggestions)})
        return render(request, 'taxon/autocomplete_suggestions.html', {'suggestions': []})

def test_autocomplete(request):
    return render(request, 'taxon/test_autocomplete.html')


class VarietyCreateView(CreateView):
    model = Variety
    form_class = VarietyForm
    template_name = 'taxon/variety_form.html'
    success_url = reverse_lazy('dashboard')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        CharacteristicFormSet = modelformset_factory(Characteristic, form=CharacteristicForm, extra=1)
        if self.request.POST:
            data['characteristic_formset'] = CharacteristicFormSet(self.request.POST)
        else:
            data['characteristic_formset'] = CharacteristicFormSet(queryset=Characteristic.objects.none())
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        characteristic_formset = context['characteristic_formset']
        if form.is_valid() and characteristic_formset.is_valid():
            self.object = form.save()
            characteristics = characteristic_formset.save(commit=False)
            for characteristic in characteristics:
                characteristic.save()
                self.object.characteristics.add(characteristic)
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        context = self.get_context_data()
        characteristic_formset = context['characteristic_formset']
        return self.render_to_response(self.get_context_data(form=form, characteristic_formset=characteristic_formset))


class TaxonCreateView(CreateView):
    model = Taxon
    form_class = TaxonForm
    template_name = 'taxon/taxon_form.html'
    success_url = reverse_lazy('dashboard')


class SynonymCreateView(CreateView):
    model = Synonym
    form_class = SynonymForm
    template_name = 'taxon/synonym_form.html'
    success_url = reverse_lazy('dashboard')


class TaxonListView(ListView):
    model = Taxon
    template_name = 'taxon/taxon_list.html'
    context_object_name = 'taxons'

    def get_context_data(self, **kwargs):
        logger.debug(f"TaxonListView get_context_data called with kwargs: {kwargs}")
        context = super().get_context_data(**kwargs)
        context['taxon_type'] = self.kwargs.get('type').capitalize()
        return context

    def get_queryset(self):
        logger.debug(f"TaxonListView get_queryset called with kwargs: {self.kwargs}")
        taxon_type = self.kwargs.get('type')
        if taxon_type == 'flower':
            return Taxon.objects.filter(type__in=['annual', 'perennial'])
        else:
            return Taxon.objects.filter(type=taxon_type)



class TaxonDetailView(DetailView):
    model = Taxon
    template_name = 'taxon/taxon_detail.html'
    context_object_name = 'taxon'



class VarietyListView(ListView):
    model = Variety
    template_name = 'taxon/variety_list.html'
    context_object_name = 'varieties'

    def get_context_data(self, **kwargs):
        logger.debug(f"VarietyListView get_context_data called with kwargs: {kwargs}")
        context = super().get_context_data(**kwargs)
        context['taxon'] = Taxon.objects.get(id=self.kwargs.get('taxon_id'))
        return context

    def get_queryset(self):
        logger.debug(f"VarietyListView get_queryset called with kwargs: {self.kwargs}")
        return Variety.objects.filter(taxon_id=self.kwargs.get('taxon_id'))


class VarietyDetailView(DetailView):
    model = Variety
    template_name = 'taxon/variety_detail.html'
    context_object_name = 'variety'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seed_lots'] = self.object.seed_lots.all()
        context['photos'] = self.object.photos.all()
        return context



def TaxonTestListView(request):
    taxons = Taxon.objects.all()
    return render(request, 'taxon/taxon_test_list.html', {'taxons': taxons})

taxon/templates/taxon/autocomplete_suggestions.html
<!-- taxon/autocomplete_suggestions.html -->
{% for suggestion in suggestions %}
    <div class="tile" data-field="name" hx-get="#" hx-trigger="click" hx-swap="outerHTML">
        {{ suggestion.name }}: {{ suggestion.value }}
    </div>
{% endfor %}

taxon/templates/taxon/characteristic_form.html
<!-- taxon/characteristic_form.html -->
{% for form in formset %}
    <div class="form-row border p-2 mb-2">
        <h3 class="text-lg font-medium">Characteristic {{ forloop.counter }}</h3>
        <label for="{{ form.name.id_for_label }}">Name:</label>
        <input type="text" name="{{ form.name.name }}" id="{{ form.name.id_for_label }}" hx-get="{% url 'characteristic-name-autocomplete' %}?term={form.name.value}" hx-trigger="input" hx-target="#{{ form.name.id_for_label }}-list" autocomplete="off">
        <ul id="{{ form.name.id_for_label }}-list" class="autocomplete-suggestions"></ul>

        <label for="{{ form.value.id_for_label }}">Value:</label>
        <input type="text" name="{{ form.value.name }}" id="{{ form.value.id_for_label }}" hx-get="{% url 'characteristic-value-autocomplete' %}?term={form.value.value}" hx-trigger="input" hx-target="#{{ form.value.id_for_label }}-list" autocomplete="off">
        <ul id="{{ form.value.id_for_label }}-list" class="autocomplete-suggestions"></ul>
    </div>
{% endfor %}

taxon/templates/taxon/fruit_list.html
{% extends "base.html" %}

{% block title %}Fruits - Seeplahar{% endblock %}

{% block content %}
<h1 class="text-3xl font-bold">Fruits</h1>
<ul>
    {% for variety in object_list %}
    <li>{{ variety.name }}</li>
    {% endfor %}
</ul>
{% endblock %}

taxon/templates/taxon/herb_list.html
{% extends "base.html" %}

{% block title %}Herbs - Seeplahar{% endblock %}

{% block content %}
<h1 class="text-3xl font-bold">Herbs</h1>
<ul>
    {% for variety in object_list %}
    <li>{{ variety.name }}</li>
    {% endfor %}
</ul>
{% endblock %}

taxon/templates/taxon/synonym_form.html
{% extends "base.html" %}

{% block title %}Add Synonym{% endblock %}

{% block content %}
<h1 class="text-3xl font-bold">Add New Synonym</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="bg-green-500 text-white px-4 py-2">Save</button>
</form>
{% endblock %}

taxon/templates/taxon/taxon_confirm_delete.html
{% extends "../../../seeplahar/templates/base.html" %}
{% block content %}
<h1>Delete Taxon</h1>
<p>Are you sure you want to delete {{ taxon.name }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'taxon_detail' taxon.pk %}">Cancel</a>
</form>
{% endblock %}

taxon/templates/taxon/taxon_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ taxon.name }} - Seeplahar{% endblock %}

{% block content %}
<div class="container mx-auto p-4">
    <div class="bg-white shadow-lg rounded-lg overflow-hidden flex">
        <div class="w-2/3 p-4">
            <div class="flex items-center justify-between border-b pb-4 mb-4">
                <h1 class="text-2xl font-bold">{{ taxon.name }}</h1>
            </div>
            <div>
                <p class="text-gray-700">{{ taxon.description }}</p>
                <div class="mt-4">
                    <h2 class="text-lg font-semibold text-center">Related Varieties</h2>
                    <ul class="mt-2">
                        {% for variety in taxon.varieties.all %}
                            <li>
                                <a href="{% url 'taxon:variety-detail' pk=variety.id %}" class="text-blue-600 hover:underline">
                                    {{ variety.name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="w-1/3 p-4 flex items-center justify-center">
            <!-- Placeholder for the photo -->
            <div class="bg-gray-200 h-64 w-full flex items-center justify-center">
                <span class="text-gray-500">Photo Placeholder</span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

taxon/templates/taxon/taxon_form.html
{% extends "base.html" %}

{% block title %}Add Taxon{% endblock %}

{% block content %}
<h1 class="text-3xl font-bold">Add New Taxon</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="bg-green-500 text-white px-4 py-2">Save</button>
</form>
{% endblock %}

taxon/templates/taxon/taxon_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ taxon_type }}{% endblock %}

{% block content %}
<h1 class="text-2xl font-bold mb-4">{{ taxon_type }}</h1>
<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4">
    {% for taxon in taxons %}
    <a href="{% url 'taxon:variety-list' type=taxon.type taxon_id=taxon.id %}" class="relative group block bg-white rounded-lg shadow-lg overflow-hidden">
        <img src="{% static 'images/' %}{{ taxon.name|lower }}.jpg" alt="{{ taxon.name }}" class="w-full h-40 object-cover">
        <div class="p-4">
            <h2 class="text-lg font-semibold">{{ taxon.name }}</h2>
            <p class="text-sm text-gray-600">{{ taxon.species_name }}</p>
        </div>
        <div class="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
            {{ taxon.name }}
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}

taxon/templates/taxon/taxon_test_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Taxon Test List - Seeplahar{% endblock %}

{% block content %}
<div class="container mx-auto p-4">
    <div class="bg-white shadow-lg rounded-lg overflow-hidden">
        <div class="p-4 border-b">
            <h1 class="text-2xl font-bold">Taxon Test List</h1>
        </div>
        <div class="p-4">
            <ul>
                {% for taxon in taxons %}
                    <li>
                        <a href="{% url 'taxon:taxon-detail' pk=taxon.pk %}" class="text-blue-600 hover:underline">{{ taxon.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

taxon/templates/taxon/variety_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ variety.name }} - Seeplahar{% endblock %}

{% block content %}
<div class="container mx-auto p-4 bg-primary-lighter rounded-lg">
    <div class="bg-white shadow-lg rounded-lg overflow-hidden flex">
        <div class="w-2/3 p-4">
            <div class="flex items-center justify-between bg-primary-light p-4 mb-4 rounded-t-lg">
                <h1 class="text-4xl font-bold text-primary-dark">{{ variety.name }}</h1>
                <a href="{% url 'taxon:taxon-detail' pk=variety.taxon.id %}" class="text-primary-dark hover:underline">{{ variety.taxon.name }}</a>
            </div>
            <div class="p-4">
                <p class="text-primary-dark">{{ variety.description }}</p>
                <div class="mt-4">
                    <h2 class="text-2xl font-semibold text-primary-dark">Seed Lots</h2>
                    <ul class="list-disc list-inside">
                        {% for seed_lot in seed_lots %}
                            <li class="text-primary">{{ seed_lot.origin }}</li>
                        {% empty %}
                            <li class="text-primary">No seed lots available.</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mt-4">
                    <table class="w-full text-left mt-2 bg-white rounded-lg">
                        <thead>
                            <tr>
                                <th class="text-center text-primary-dark" colspan="2">Characteristics</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for characteristic in variety.characteristics.all %}
                                <tr class="border-b">
                                    <td class="pr-4 font-semibold text-right bg-primary-light rounded-l-lg">{{ characteristic.name }}</td>
                                    <td class="pl-4 text-left text-primary-dark bg-white rounded-r-lg">{{ characteristic.value }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="w-1/3 p-4 flex items-center justify-center">
            <div class="bg-gray-200 h-64 w-full flex items-center justify-center rounded-lg">
                <span class="text-gray-500">Photo Placeholder</span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

taxon/templates/taxon/variety_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ taxon.name }} Varieties{% endblock %}

{% block content %}
<h1 class="text-2xl font-bold mb-4">{{ taxon.name }} Varieties</h1>
<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4">
    {% for variety in varieties %}
    <a href="{% url 'generic-detail' pk=variety.id %}" class="relative group block bg-white rounded-lg shadow-lg overflow-hidden">
        <img src="{% static 'images/' %}{{ variety.name|lower }}.jpg" alt="{{ variety.name }}" class="w-full h-40 object-cover">
        <div class="p-4">
            <h2 class="text-lg font-semibold">{{ variety.name }}</h2>
            <p class="text-sm text-gray-600">{{ variety.description }}</p>
        </div>
        <div class="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 text-white text-xl font-bold opacity-0 group-hover:opacity-100 transition-opacity">
            {{ variety.name }}
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}